const customIcons = [
  'profile', 'addProfile', 'view', 'hideView', 'documents', 'registrationRenewal',
  'checklist', 'carPool', 'ellipsesHorizontal', 'ellipsesVertical', 'filterControl',
  'burger', 'mapPassport', 'maintenanceHistory', 'pdf', 'images', 'settings', 'find',
  'location', 'code', 'calendar', 'calendarRange', 'calendarTime', 'bin', 'notification',
  'notificationActive', 'evCharging', 'fuel', 'toolsAndViolations', 'price', 'minusCircle',
  'plusCircle', 'sustainability', 'reimburse', 'remarketing', 'positiveReinforcement',
  'timeRemaining', 'send', 'share', 'pay', 'creditCard', 'maintenanceAndRepair',
  'agreement', 'mileage', 'purchase', 'purchaseItem', 'email', 'emailActive', 'trips',
  'call', 'bookAVehicle', 'car', 'truck', 'van', 'forklift', 'telematics', 'chevronRight',
  'chevronRightLine', 'chevronLeftLine', 'chevronDown', 'chevronUp', 'chevronLeft',
  'arrowRight', 'arrowLeft', 'arrowUp', 'arrowDown', 'lease', 'owner', 'rentACar',
  'search', 'sortUp', 'sortDown', 'directions', 'performance', 'intersectingArrows',
  'phone', 'chat', 'serviceDue', 'recall',
    'odometer', 'copy', 'plus', 'minus', 'cross', 'urgent', 'chart', 'video', 'camera',
  'phoneSimple', 'play', 'playFilled', 'pause', 'trafficLight', 'windscreenRepair',
  'carwash', 'discount', 'dashboard', 'reload', 'export', 'download', 'upload',
  'blackOwned', 'womenOwned', 'veteranOwned', 'familyOwned', 'attach', 'link', 'star',
  'like', 'fuelEconomy', 'co2Emissions', 'idleUsage', 'newVehicleOrder', 'number',
  'verifyData', 'edit', 'starFilled', 'merge', 'home', 'lock', 'updates', 'connected',
  'fax', 'filterTable', 'filter', 'logout', 'fleetPolicy', 'questions', 'submitMiles',
  'singleTracking', 'manualEntry', 'flexibleTracking', 'automaticTracking',
  'insuranceEffective', 'plateInfo', 'mvr', 'training', 'services', 'requestHelp',
  'customize', 'bookmark', 'division', 'save', 'bold', 'italic', 'underline',
  'alignLeft', 'alignRight', 'alignCenter', 'justify', 'clock', 'success', 'successSmall',
  'warning', 'warningSmall', 'error', 'errorSmall', 'info', 'infoOutline', 'infoSmall',
  'progress', 'progressSmall', 'rotateLeft', 'rotateRight', 'scan', 'on', 'questionsPlain',
  'unpin', 'celebrationOutline', 'drag', 'list', 'pin', 'pinned', 'select', 'unpinned',
  'mapStart', 'mapEnd', 'collapse', 'expand', 'keyboard', 'oil', 'brake', 'calendarSingle',
  'progressOutline', 'newVehicleShine', 'recommendation', 'webpage', 'replaceVehicle',
  'retainVehicle', 'new', 'battery', 'tirePressure', 'airFilter', 'connectedVehicle'

];
export default customIcons;